### ISSUE TITLE
As an artist apart of a collaboration effort I would like to have an account we all can access so we can share credit for the art.

### ISSUE THREAD

**Issue by adard2002** [DeltaVArtLibrary/DigitalArtHub#23]
1. Create the Profile (*GROUP)
- Require a logged in user
- Add Logged in user as Profile Owner
- Require a profile name
- Allow a description
- Allow privacy setting default to public
- Return Profile DTO

2. Add members
- Authorize for Profile Admin
- Require Valid user ID for addition
- Don't allow for private users
- Allow permission level default to member
- Maybe allow added user to confirm the addition
- Return Profile DTO
- If user ID is invalid return a 404 error with body saying "member not found" or something of that sort

3. Remove member
- Authorize for profile admin or higher
- Require profile member ID with permission less than current user
- Return Profile DTO
- Remove member

4. Change member permissions
- Authorize for profile admin or higher
- Require profile member
- Require permission level less than current user
- If profile member level is higher than new level throw bad request
- If permission level is higher than current user level throw bad request
- Set profile member permission to designated level
- Return Profile DTO

**Comment by jmcia2020** [comment]
Controller -
